Alias /static /home/monirgro/monirapi.ramsint.com/static
<Directory /home/monirgro/monirapi.ramsint.com/static>
    Require all granted
</Directory>

Alias /media /home/monirgro/monirapi.ramsint.com/media
<Directory /home/monirgro/monirapi.ramsint.com/media>
    Require all granted
</Directory>

# Use different process names for HTTP and HTTPS
<IfModule mod_wsgi.c>
    <IfDefine PORT_8181>
        WSGIDaemonProcess monirapi.ramsint.com python-path=/home/monirgro/monirapi.ramsint.com python-home=/home/monirgro/monirapi.ramsint.com/env
        WSGIProcessGroup monirapi.ramsint.com
    </IfDefine>
    <IfDefine PORT_8443>
        #WSGIDaemonProcess monirapi.ramsint.com python-path=/home/monirgro/monirapi.ramsint.com python-home=/home/monirgro/monirapi.ramsint.com/env
        #WSGIProcessGroup monirapi.ramsint.com
    </IfDefine>
</IfModule>

WSGIPassAuthorization On
WSGIScriptAlias / /home/monirgro/monirapi.ramsint.com/start_project/wsgi.py

<Directory /home/monirgro/monirapi.ramsint.com/start_project>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>
